import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'

const routes = [
  {
    path: '/',
    name: 'home',
    component: HomeView,
  },
  {
    path: '/tools',
    redirect: '/tools/strlen',
  },
  {
    path: '/tools',
    component: () => import('@/views/ToolsView.vue'),
    children: [
      { path: 'countdown', component: () => import('@/views/tools/CountdownToolPage.vue') },
      { path: 'random', component: () => import('@/views/tools/RandomToolPage.vue') },
      { path: 'qr', component: () => import('@/views/tools/QRToolPage.vue') },
      { path: 'datediff', component: () => import('@/views/tools/DateDiffToolPage.vue') },
      { path: 'lengthconvert', component: () => import('@/views/tools/LengthConvertToolPage.vue') },
      { path: 'note', component: () => import('@/views/tools/NoteToolPage.vue') },
      { path: 'rate', component: () => import('@/views/tools/RateToolPage.vue') },
      {
        path: 'douyindownload',
        component: () => import('@/views/tools/DouyinDownloadToolPage.vue'),
      },
      { path: 'regex', component: () => import('@/views/tools/RegexTestToolPage.vue') },
      { path: 'base64', component: () => import('@/views/tools/Base64ToolPage.vue') },
      { path: 'timestamp', component: () => import('@/views/tools/TimestampToolPage.vue') },
      { path: 'uuid', component: () => import('@/views/tools/UuidToolPage.vue') },
      { path: 'radixconvert', component: () => import('@/views/tools/RadixConvertToolPage.vue') },
      { path: 'urlencode', component: () => import('@/views/tools/UrlEncodeToolPage.vue') },
      { path: 'strlen', component: () => import('@/views/tools/StrLenToolPage.vue') },
      { path: 'dailyquote', component: () => import('@/views/tools/DailyQuoteToolPage.vue') },
      { path: 'emojiwall', component: () => import('@/views/tools/EmojiWallToolPage.vue') },
      { path: 'randomfact', component: () => import('@/views/tools/RandomFactToolPage.vue') },
      { path: 'luckycolor', component: () => import('@/views/tools/LuckyColorToolPage.vue') },
      { path: 'fishcountdown', component: () => import('@/views/tools/FishCountdownToolPage.vue') },
      { path: 'weather', component: () => import('@/views/tools/WeatherToolPage.vue') },
      { path: 'poem', component: () => import('@/views/tools/PoemToolPage.vue') },
      { path: 'jsondiff', component: () => import('@/views/tools/JsonDiffToolPage.vue') },
      { path: 'liuyao', component: () => import('@/views/tools/LiuyaoToolPage.vue') },
      { path: 'md5', component: () => import('@/views/tools/Md5ToolPage.vue') },
      { path: 'colorconvert', component: () => import('@/views/tools/ColorConvertToolPage.vue') },
      { path: 'textdedup', component: () => import('@/views/tools/TextDedupToolPage.vue') },
      { path: 'uuidbatch', component: () => import('@/views/tools/UuidBatchToolPage.vue') },
      { path: 'jsonformat', component: () => import('@/views/tools/JsonFormatToolPage.vue') },
      { path: 'idcard', component: () => import('@/views/tools/IdCardToolPage.vue') },
      { path: 'chinesepinyin', component: () => import('@/views/tools/ChinesePinyinToolPage.vue') },
      { path: 'calendar', component: () => import('@/views/tools/CalendarToolPage.vue') },
      { path: 'agecalc', component: () => import('@/views/tools/AgeCalcToolPage.vue') },
      { path: 'passwordgen', component: () => import('@/views/tools/PasswordGenToolPage.vue') },
      { path: 'notepad', component: () => import('@/views/tools/NotepadToolPage.vue') },
      { path: 'unitconvert', component: () => import('@/views/tools/UnitConvertToolPage.vue') },
      { path: 'ipquery', component: () => import('@/views/tools/IpQueryToolPage.vue') },
      { path: 'mobilequery', component: () => import('@/views/tools/MobileQueryToolPage.vue') },
      { path: 'bmi', component: () => import('@/views/tools/BmiToolPage.vue') },
      { path: 'tipcalc', component: () => import('@/views/tools/TipCalcToolPage.vue') },
      { path: 'moneyupper', component: () => import('@/views/tools/MoneyUpperToolPage.vue') },
      { path: 'text2voice', component: () => import('@/views/tools/Text2VoiceToolPage.vue') },
      { path: 'img2base64', component: () => import('@/views/tools/Img2Base64ToolPage.vue') },
      { path: 'shorturl', component: () => import('@/views/tools/ShortUrlToolPage.vue') },
      { path: 'colorpicker', component: () => import('@/views/tools/ColorPickerToolPage.vue') },
      { path: 'progressbar', component: () => import('@/views/tools/ProgressBarToolPage.vue') },
      { path: 'zodiac', component: () => import('@/views/tools/ZodiacToolPage.vue') },
      { path: 'relatives', component: () => import('@/views/tools/RelativesToolPage.vue') },
      { path: 'billbook', component: () => import('@/views/tools/BillBookToolPage.vue') },
      { path: 'han2unicode', component: () => import('@/views/tools/Han2UnicodeToolPage.vue') },
      { path: 'unicode2han', component: () => import('@/views/tools/Unicode2HanToolPage.vue') },
      {
        path: 'colorallconvert',
        component: () => import('@/views/tools/ColorAllConvertToolPage.vue'),
      },
      { path: 'asciiconvert', component: () => import('@/views/tools/AsciiConvertToolPage.vue') },
      { path: 'ipconvert', component: () => import('@/views/tools/IpConvertToolPage.vue') },
      { path: 'htmlentity', component: () => import('@/views/tools/HtmlEntityToolPage.vue') },
      { path: 'morse', component: () => import('@/views/tools/MorseToolPage.vue') },
      { path: 'idcardcheck', component: () => import('@/views/tools/IdCardCheckToolPage.vue') },
      { path: 'bankcardcheck', component: () => import('@/views/tools/BankCardCheckToolPage.vue') },
      { path: 'randomname', component: () => import('@/views/tools/RandomNameToolPage.vue') },
    ],
  },
  { path: '/blog', component: () => import('@/views/blog/BlogHome.vue') },
  { path: '/blog/login', component: () => import('@/views/blog/BlogLogin.vue') },
  { path: '/blog/register', component: () => import('@/views/blog/BlogRegister.vue') },
  {
    path: '/blog/article/:id',
    component: () => import('@/views/blog/BlogArticleDetail.vue'),
    props: true,
  },
  { path: '/blog/my', component: () => import('@/views/blog/BlogMyArticles.vue') },
  { path: '/blog/create', component: () => import('@/views/blog/BlogCreateArticle.vue') },
]

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes,
})

export default router
